/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Marketplace {
  export type NftItemStruct = { price: BigNumberish; owner: AddressLike };

  export type NftItemStructOutput = [price: bigint, owner: string] & {
    price: bigint;
    owner: string;
  };
}

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "buyNft"
      | "getNft"
      | "listNft"
      | "unlistNft"
      | "updateNftPrice"
      | "withdrawBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NftListedOn"
      | "NftPriceUpdated"
      | "NftPurchased"
      | "NftUnlisted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNft",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNft",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listNft",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlistNft",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNftPrice",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlistNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNftPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
}

export namespace NftListedOnEvent {
  export type InputTuple = [
    nftAddress: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    nftAddress: string,
    tokenId: bigint,
    price: bigint
  ];
  export interface OutputObject {
    nftAddress: string;
    tokenId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NftPriceUpdatedEvent {
  export type InputTuple = [
    nftAddress: AddressLike,
    tokenId: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    nftAddress: string,
    tokenId: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    nftAddress: string;
    tokenId: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NftPurchasedEvent {
  export type InputTuple = [
    nftAddress: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    nftAddress: string,
    tokenId: bigint,
    price: bigint
  ];
  export interface OutputObject {
    nftAddress: string;
    tokenId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NftUnlistedEvent {
  export type InputTuple = [nftAddress: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [nftAddress: string, tokenId: bigint];
  export interface OutputObject {
    nftAddress: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  buyNft: TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  getNft: TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [Marketplace.NftItemStructOutput],
    "view"
  >;

  listNft: TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlistNft: TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateNftPrice: TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyNft"
  ): TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getNft"
  ): TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [Marketplace.NftItemStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listNft"
  ): TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlistNft"
  ): TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateNftPrice"
  ): TypedContractMethod<
    [nftAddress: AddressLike, tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "NftListedOn"
  ): TypedContractEvent<
    NftListedOnEvent.InputTuple,
    NftListedOnEvent.OutputTuple,
    NftListedOnEvent.OutputObject
  >;
  getEvent(
    key: "NftPriceUpdated"
  ): TypedContractEvent<
    NftPriceUpdatedEvent.InputTuple,
    NftPriceUpdatedEvent.OutputTuple,
    NftPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NftPurchased"
  ): TypedContractEvent<
    NftPurchasedEvent.InputTuple,
    NftPurchasedEvent.OutputTuple,
    NftPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "NftUnlisted"
  ): TypedContractEvent<
    NftUnlistedEvent.InputTuple,
    NftUnlistedEvent.OutputTuple,
    NftUnlistedEvent.OutputObject
  >;

  filters: {
    "NftListedOn(address,uint256,uint256)": TypedContractEvent<
      NftListedOnEvent.InputTuple,
      NftListedOnEvent.OutputTuple,
      NftListedOnEvent.OutputObject
    >;
    NftListedOn: TypedContractEvent<
      NftListedOnEvent.InputTuple,
      NftListedOnEvent.OutputTuple,
      NftListedOnEvent.OutputObject
    >;

    "NftPriceUpdated(address,uint256,uint256)": TypedContractEvent<
      NftPriceUpdatedEvent.InputTuple,
      NftPriceUpdatedEvent.OutputTuple,
      NftPriceUpdatedEvent.OutputObject
    >;
    NftPriceUpdated: TypedContractEvent<
      NftPriceUpdatedEvent.InputTuple,
      NftPriceUpdatedEvent.OutputTuple,
      NftPriceUpdatedEvent.OutputObject
    >;

    "NftPurchased(address,uint256,uint256)": TypedContractEvent<
      NftPurchasedEvent.InputTuple,
      NftPurchasedEvent.OutputTuple,
      NftPurchasedEvent.OutputObject
    >;
    NftPurchased: TypedContractEvent<
      NftPurchasedEvent.InputTuple,
      NftPurchasedEvent.OutputTuple,
      NftPurchasedEvent.OutputObject
    >;

    "NftUnlisted(address,uint256)": TypedContractEvent<
      NftUnlistedEvent.InputTuple,
      NftUnlistedEvent.OutputTuple,
      NftUnlistedEvent.OutputObject
    >;
    NftUnlisted: TypedContractEvent<
      NftUnlistedEvent.InputTuple,
      NftUnlistedEvent.OutputTuple,
      NftUnlistedEvent.OutputObject
    >;
  };
}
