/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as greekSol from "./Greek.sol";
export * as myTokenSol from "./MyToken.sol";
export { MyTokenURI__factory } from "./MyTokenURI__factory";
