/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greekSol from "./Greek.sol";
export type { greekSol };
import type * as myTokenSol from "./MyToken.sol";
export type { myTokenSol };
export type { MyTokenURI } from "./MyTokenURI";
